[topics]
log = "sar:log"
input = "sar:input"
echo = "sar:echo"
reverse = "sar:reverse"
server = "sar:server"

[server]
host = "127.0.0.1"
port = 3000

[ui]
show_bottom_panel = true

[llm]
model = "gpt-4o-mini"
base_url = "http://ayourtch-desktop:8000/v1"
api_key = ""
temperature = 0.7
max_tokens = 65536

[ui_hubs.default]
name = "default"
user_topic = "ui:user"
input_topic = "ui:input"
buffer_size = 1000
subscribe_to = ["sar:echo", "sar:reverse", "llm-test-tools:0:stream", "llm:0:stats"]
route_to = ["llm-test-tools:0:in"]

[mcp_servers.find_files]
command = ["/Users/ayourtch/rust/mcp-find-files/target/debug/mcp-find-files"]
default = true
[mcp_servers.read_file]
command = ["/Users/ayourtch/rust/mcp-read-file/target/debug/mcp-read-file"]
default = true
