[topics]
log = "sar:log"
input = "sar:input"
echo = "sar:echo"
reverse = "sar:reverse"
server = "sar:server"

[server]
host = "127.0.0.1"
port = 3000

[ui]
show_bottom_panel = true

[llm]
model = "qwen3.5-long:latest"
base_url = "http://gx10-96b6:8080/v1"
api_key = ""
temperature = 0.7
max_tokens = 65536

[ui_hubs.default]
name = "default"
user_topic = "ui:user"
input_topic = "ui:input"
buffer_size = 1000
subscribe_to = ["sar:echo", "sar:reverse", "llm-test-tools:0:stream", "llm:0:stats"]
route_to = ["llm-test-tools:0:in"]

[system_message]
message = "You are a helpful assistant. You are not overthinking things. You are professional and confident. All your changes will later be reviewed by Codex, so you do your best!"
allow_edit = true

[mcp_servers.find_files]
command = ["/Users/ayourtch/rust/mcp-find-files/target/debug/mcp-find-files"]
default = true
[mcp_servers.read_file]
command = ["/Users/ayourtch/rust/mcp-read-file/target/debug/mcp-read-file"]
default = true
[mcp_servers.run_command]
command = ["/Users/ayourtch/rust/mcp-run-command/target/debug/mcp-run-command"]
default = true
